/**
 * Cognitive node catalog: maps BullMQ queue names (registry values) to neuron taxonomy.
 * Per-phone WhatsApp queues `q:wa:phone-NN` and `q:wa:phone-NN:followup` (N=01..20) are
 * generated at runtime by getWaPhoneQueueName / getWaPhoneFollowupQueueName — not listed here.
 *
 * @see workers/shared/src/queue-registry.ts
 */

export type NeuronType =
  | "SENSORY"
  | "NORMALIZATION"
  | "REFLEX"
  | "FACTUAL"
  | "DISCOVERY"
  | "DELIBERATIVE"
  | "SPATIAL"
  | "DOMAIN"
  | "PATTERN"
  | "META"
  | "EXECUTIVE"
  | "MAINTENANCE"
  | "HUMAN"
  | "ATTENTION"
  | "EMOTION"
  | "PROCEDURAL"
  | "AUTONOMIC"
  | "VIGILANCE"
  | "MOTOR";

export type Swimlane =
  | "data-ingest"
  | "normalization"
  | "validation"
  | "enrichment-fiscal"
  | "enrichment-external"
  | "ai-analysis"
  | "dedup-scoring"
  | "pipeline-control"
  | "human-oversight"
  | "social-action";

export type Criticality = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

export interface CognitiveNodeEntry {
  nodeKey: string;
  queueName: string;
  displayName: string;
  cognitiveFunction: string;
  biologicalAnalogy: string;
  neuronType: NeuronType;
  swimlane: Swimlane;
  etapa: 1 | 2 | 3 | 4 | 5;
  criticality: Criticality;
  pulsing: boolean;
}

function nodeKeyFromQueue(queueName: string): string {
  return `worker:${queueName.replace(/:/g, "-")}`;
}

/** Etapa 1 — data & enrichment pipeline */
const E1: CognitiveNodeEntry[] = [
  // Sensory — data-ingest
  {
    nodeKey: nodeKeyFromQueue("ingest:csv"),
    queueName: "ingest:csv",
    displayName: "CSV ingest",
    cognitiveFunction: "Admit tabular file streams into working memory",
    biologicalAnalogy: "Primary afferents transducing structured stimuli",
    neuronType: "SENSORY",
    swimlane: "data-ingest",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ingest:excel"),
    queueName: "ingest:excel",
    displayName: "Excel ingest",
    cognitiveFunction: "Parse spreadsheet payloads into canonical records",
    biologicalAnalogy: "Somatosensory pathways for complex surface patterns",
    neuronType: "SENSORY",
    swimlane: "data-ingest",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ingest:webhook"),
    queueName: "ingest:webhook",
    displayName: "Webhook ingest",
    cognitiveFunction: "Capture event-driven external signals in real time",
    biologicalAnalogy: "Rapid sensory relay from peripheral receptors",
    neuronType: "SENSORY",
    swimlane: "data-ingest",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ingest:manual"),
    queueName: "ingest:manual",
    displayName: "Manual ingest",
    cognitiveFunction: "Integrate operator-initiated data entry",
    biologicalAnalogy: "Voluntary sensory channels from motor-sensory loops",
    neuronType: "SENSORY",
    swimlane: "data-ingest",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("ingest:api"),
    queueName: "ingest:api",
    displayName: "API ingest",
    cognitiveFunction: "Pull or accept programmatic data feeds",
    biologicalAnalogy: "Dedicated sensory nuclei for remote modality input",
    neuronType: "SENSORY",
    swimlane: "data-ingest",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  // Normalization
  {
    nodeKey: nodeKeyFromQueue("normalize:name"),
    queueName: "normalize:name",
    displayName: "Name normalization",
    cognitiveFunction: "Standardize entity names for identity resolution",
    biologicalAnalogy: "Pattern-completion in association cortex",
    neuronType: "NORMALIZATION",
    swimlane: "normalization",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("normalize:address"),
    queueName: "normalize:address",
    displayName: "Address normalization",
    cognitiveFunction: "Canonicalize postal and location strings",
    biologicalAnalogy: "Spatial frame alignment in parietal maps",
    neuronType: "NORMALIZATION",
    swimlane: "normalization",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("normalize:phone"),
    queueName: "normalize:phone",
    displayName: "Phone normalization",
    cognitiveFunction: "Normalize dial strings and country formats",
    biologicalAnalogy: "Temporal pattern regularization in auditory belt",
    neuronType: "NORMALIZATION",
    swimlane: "normalization",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("normalize:email"),
    queueName: "normalize:email",
    displayName: "Email normalization",
    cognitiveFunction: "Lowercase, trim, and validate mailbox forms",
    biologicalAnalogy: "Lexical normalization before semantic binding",
    neuronType: "NORMALIZATION",
    swimlane: "normalization",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:bronze:anaf"),
    queueName: "enrich:bronze:anaf",
    displayName: "Bronze ANAF enrichment",
    cognitiveFunction: "Attach fiscal registry identifiers at bronze tier",
    biologicalAnalogy: "Early cortical sharpening of noisy registry signals",
    neuronType: "NORMALIZATION",
    swimlane: "normalization",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  // Reflex — validation
  {
    nodeKey: nodeKeyFromQueue("validate:cui:mod11"),
    queueName: "validate:cui:mod11",
    displayName: "CUI Mod-11 validation",
    cognitiveFunction: "Fast checksum validation of fiscal identifiers",
    biologicalAnalogy: "Spinal reflex arc — immediate integrity check",
    neuronType: "REFLEX",
    swimlane: "validation",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("validate:cui:anaf"),
    queueName: "validate:cui:anaf",
    displayName: "CUI ANAF validation",
    cognitiveFunction: "Authoritative registry confirmation of CUI",
    biologicalAnalogy: "Brainstem-mediated verification against body schema",
    neuronType: "REFLEX",
    swimlane: "validation",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: true,
  },
  // Factual — enrichment-fiscal
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:full"),
    queueName: "enrich:anaf:full",
    displayName: "ANAF full enrichment",
    cognitiveFunction: "Unified fiscal profile from national registry",
    biologicalAnalogy: "Declarative memory consolidation from official records",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:fiscal-status"),
    queueName: "enrich:anaf:fiscal-status",
    displayName: "ANAF fiscal status",
    cognitiveFunction: "Fiscal standing snapshot from ANAF",
    biologicalAnalogy: "Fact retrieval from long-term semantic store",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:tva-status"),
    queueName: "enrich:anaf:tva-status",
    displayName: "ANAF TVA status",
    cognitiveFunction: "VAT registration and status enrichment",
    biologicalAnalogy: "Specialized factual channel for tax modality",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:efactura"),
    queueName: "enrich:anaf:efactura",
    displayName: "ANAF e-Factura",
    cognitiveFunction: "Electronic invoicing registry linkage",
    biologicalAnalogy: "Auditory-like trace binding for transactional facts",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:datorii"),
    queueName: "enrich:anaf:datorii",
    displayName: "ANAF debts",
    cognitiveFunction: "Public debt indicators from ANAF",
    biologicalAnalogy: "Risk salience encoding in factual circuits",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:anaf:caen"),
    queueName: "enrich:anaf:caen",
    displayName: "ANAF CAEN",
    cognitiveFunction: "Activity code classification enrichment",
    biologicalAnalogy: "Categorical labeling in ventral stream",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:termene:balance"),
    queueName: "enrich:termene:balance",
    displayName: "Termene balance",
    cognitiveFunction: "Balance-sheet signals from legal/commercial data",
    biologicalAnalogy: "Proprioceptive balance readout of firm posture",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:termene:risk"),
    queueName: "enrich:termene:risk",
    displayName: "Termene risk",
    cognitiveFunction: "Litigation and risk scoring enrichment",
    biologicalAnalogy: "Amygdala-linked threat appraisal from case law",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:termene:dosare"),
    queueName: "enrich:termene:dosare",
    displayName: "Termene dosare",
    cognitiveFunction: "Case file dossier enrichment",
    biologicalAnalogy: "Episodic memory traces of legal episodes",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:termene:actionari"),
    queueName: "enrich:termene:actionari",
    displayName: "Termene shareholders",
    cognitiveFunction: "Shareholder structure enrichment",
    biologicalAnalogy: "Social graph facts in temporal-parietal hub",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:onrc:data"),
    queueName: "enrich:onrc:data",
    displayName: "ONRC core data",
    cognitiveFunction: "Trade registry core record enrichment",
    biologicalAnalogy: "Hippocampal indexing of institutional identity",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:onrc:administratori"),
    queueName: "enrich:onrc:administratori",
    displayName: "ONRC administrators",
    cognitiveFunction: "Officer and administrator roster enrichment",
    biologicalAnalogy: "Agent representation in social cognition network",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:onrc:sedii"),
    queueName: "enrich:onrc:sedii",
    displayName: "ONRC premises",
    cognitiveFunction: "Registered office and branch enrichment",
    biologicalAnalogy: "Place cells anchoring firm locations",
    neuronType: "FACTUAL",
    swimlane: "enrichment-fiscal",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  // Discovery — enrichment-external (email, phone, scrape)
  {
    nodeKey: nodeKeyFromQueue("discover:email:hunter"),
    queueName: "discover:email:hunter",
    displayName: "Discover email (Hunter)",
    cognitiveFunction: "Prospect corporate emails via external directory",
    biologicalAnalogy: "Exploratory saccades in visual search",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("discover:email:hunter-verify"),
    queueName: "discover:email:hunter-verify",
    displayName: "Verify email (Hunter)",
    cognitiveFunction: "Confirm deliverability of discovered addresses",
    biologicalAnalogy: "Re-entrant validation loop in attention",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("discover:email:zerobounce"),
    queueName: "discover:email:zerobounce",
    displayName: "Discover/verify (ZeroBounce)",
    cognitiveFunction: "Third-party email validity signals",
    biologicalAnalogy: "Cross-modal corroboration of contact hypotheses",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:email:enricher"),
    queueName: "enrich:email:enricher",
    displayName: "Email enricher",
    cognitiveFunction: "Deep metadata enrichment for mail identities",
    biologicalAnalogy: "Feature binding in ventral object pathway",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("discover:email:pattern"),
    queueName: "discover:email:pattern",
    displayName: "Email pattern discovery",
    cognitiveFunction: "Infer likely addresses from naming patterns",
    biologicalAnalogy: "Predictive coding filling missing perceptual data",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("discover:email:generate"),
    queueName: "discover:email:generate",
    displayName: "Email generation",
    cognitiveFunction: "Generate candidate emails for verification",
    biologicalAnalogy: "Divergent generative sampling in prefrontal cortex",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:phone:normalize"),
    queueName: "enrich:phone:normalize",
    displayName: "Phone enrich normalize",
    cognitiveFunction: "Carrier-agnostic phone canonicalization",
    biologicalAnalogy: "Cochlear-like frequency-place remapping",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:phone:hlr"),
    queueName: "enrich:phone:hlr",
    displayName: "Phone HLR lookup",
    cognitiveFunction: "Live mobile routing and validity via HLR",
    biologicalAnalogy: "Remote sensing of line-of-sight to subscriber",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("enrich:phone:carrier"),
    queueName: "enrich:phone:carrier",
    displayName: "Phone carrier",
    cognitiveFunction: "Carrier and line-type inference",
    biologicalAnalogy: "Modality tagging for communication channels",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("scrape:legal:daj"),
    queueName: "scrape:legal:daj",
    displayName: "Scrape legal DAJ",
    cognitiveFunction: "Harvest agricultural legal notices",
    biologicalAnalogy: "Active foraging along information gradients",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("scrape:legal:anif"),
    queueName: "scrape:legal:anif",
    displayName: "Scrape legal ANIF",
    cognitiveFunction: "Harvest inspection and sanction data",
    biologicalAnalogy: "Peripheral sweep for salient regulatory cues",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("scrape:website:finder"),
    queueName: "scrape:website:finder",
    displayName: "Website finder",
    cognitiveFunction: "Locate official web presence for entities",
    biologicalAnalogy: "Scene parsing to find target objects",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("scrape:website:contact-page"),
    queueName: "scrape:website:contact-page",
    displayName: "Contact page scrape",
    cognitiveFunction: "Extract contact surfaces from web pages",
    biologicalAnalogy: "Fine-grained foveation on high-value regions",
    neuronType: "DISCOVERY",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Deliberative — ai-analysis
  {
    nodeKey: nodeKeyFromQueue("ai:structure:xai"),
    queueName: "ai:structure:xai",
    displayName: "AI structure (XAI)",
    cognitiveFunction: "Explainable structuring of unstructured text",
    biologicalAnalogy: "Prefrontal executive decomposition of narratives",
    neuronType: "DELIBERATIVE",
    swimlane: "ai-analysis",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ai:merge:xai"),
    queueName: "ai:merge:xai",
    displayName: "AI merge (XAI)",
    cognitiveFunction: "Reconcile conflicting extractions with rationale",
    biologicalAnalogy: "Working-memory merge and conflict resolution",
    neuronType: "DELIBERATIVE",
    swimlane: "ai-analysis",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ai:score:confidence"),
    queueName: "ai:score:confidence",
    displayName: "AI confidence score",
    cognitiveFunction: "Quantify belief in field-level extractions",
    biologicalAnalogy: "Metacognitive confidence signals",
    neuronType: "DELIBERATIVE",
    swimlane: "ai-analysis",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ai:fallback"),
    queueName: "ai:fallback",
    displayName: "AI fallback",
    cognitiveFunction: "Degraded-mode reasoning when primary AI fails",
    biologicalAnalogy: "Recruitment of backup cortical circuits",
    neuronType: "DELIBERATIVE",
    swimlane: "ai-analysis",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  // Spatial
  {
    nodeKey: nodeKeyFromQueue("geo:geocode:nominatim"),
    queueName: "geo:geocode:nominatim",
    displayName: "Geocode (Nominatim)",
    cognitiveFunction: "Resolve addresses to coordinates",
    biologicalAnalogy: "Grid and place coding in entorhinal-hippocampal loop",
    neuronType: "SPATIAL",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("geo:zones:postgis"),
    queueName: "geo:zones:postgis",
    displayName: "Geo zones (PostGIS)",
    cognitiveFunction: "Assign regions, zones, and polygons",
    biologicalAnalogy: "Border cells delineating territorial partitions",
    neuronType: "SPATIAL",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("geo:proximity"),
    queueName: "geo:proximity",
    displayName: "Geo proximity",
    cognitiveFunction: "Neighborhood and distance scoring",
    biologicalAnalogy: "Distance-tuned parietal population codes",
    neuronType: "SPATIAL",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Domain — agri
  {
    nodeKey: nodeKeyFromQueue("agri:apia"),
    queueName: "agri:apia",
    displayName: "Agri APIA",
    cognitiveFunction: "Agricultural subsidy and plot linkage",
    biologicalAnalogy: "Domain-specific module for agro-semantic facts",
    neuronType: "DOMAIN",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("agri:ouai"),
    queueName: "agri:ouai",
    displayName: "Agri OUAI",
    cognitiveFunction: "Veterinary and farm registration enrichment",
    biologicalAnalogy: "Specialized schema for livestock identity",
    neuronType: "DOMAIN",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("agri:cooperative"),
    queueName: "agri:cooperative",
    displayName: "Agri cooperative",
    cognitiveFunction: "Cooperative membership and structure",
    biologicalAnalogy: "Social-cluster labeling in niche cortex",
    neuronType: "DOMAIN",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("agri:culturi"),
    queueName: "agri:culturi",
    displayName: "Agri crops",
    cognitiveFunction: "Crop and cultivation declarations",
    biologicalAnalogy: "Categorical agronomic feature detectors",
    neuronType: "DOMAIN",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("agri:animale"),
    queueName: "agri:animale",
    displayName: "Agri animals",
    cognitiveFunction: "Herd and animal registry linkage",
    biologicalAnalogy: "Inventory-like tally circuits for animate assets",
    neuronType: "DOMAIN",
    swimlane: "enrichment-external",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  // Pattern / Meta — dedup-scoring
  {
    nodeKey: nodeKeyFromQueue("dedup:exact"),
    queueName: "dedup:exact",
    displayName: "Exact deduplication",
    cognitiveFunction: "Collapse deterministic duplicate keys",
    biologicalAnalogy: "Pattern separation in dentate gyrus",
    neuronType: "PATTERN",
    swimlane: "dedup-scoring",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("dedup:fuzzy"),
    queueName: "dedup:fuzzy",
    displayName: "Fuzzy deduplication",
    cognitiveFunction: "Probabilistic merge of near-duplicate entities",
    biologicalAnalogy: "Attractor dynamics merging similar traces",
    neuronType: "PATTERN",
    swimlane: "dedup-scoring",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("score:completeness"),
    queueName: "score:completeness",
    displayName: "Completeness score",
    cognitiveFunction: "Measure field coverage and mandatory gaps",
    biologicalAnalogy: "Global workspace fullness signal",
    neuronType: "META",
    swimlane: "dedup-scoring",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("score:accuracy"),
    queueName: "score:accuracy",
    displayName: "Accuracy score",
    cognitiveFunction: "Contrast predictions with ground-truth checks",
    biologicalAnalogy: "Error-monitoring ERP-like internal feedback",
    neuronType: "META",
    swimlane: "dedup-scoring",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("score:freshness"),
    queueName: "score:freshness",
    displayName: "Freshness score",
    cognitiveFunction: "Temporal decay and recency of sourced facts",
    biologicalAnalogy: "Synaptic tagging for memory age",
    neuronType: "META",
    swimlane: "dedup-scoring",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Maintenance — aggregates
  {
    nodeKey: nodeKeyFromQueue("aggregate:daily-stats"),
    queueName: "aggregate:daily-stats",
    displayName: "Daily stats aggregate",
    cognitiveFunction: "Roll up operational counters for reporting",
    biologicalAnalogy: "Homeostatic tally neurons in hypothalamus-like hub",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("aggregate:quality-rollup"),
    queueName: "aggregate:quality-rollup",
    displayName: "Quality rollup",
    cognitiveFunction: "Summarize data-quality dimensions",
    biologicalAnalogy: "Integrative interneurons pooling quality gist",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "MEDIUM",
    pulsing: false,
  },
  // Executive / pipeline-control
  {
    nodeKey: nodeKeyFromQueue("pipeline:orchestrate"),
    queueName: "pipeline:orchestrate",
    displayName: "Pipeline orchestrate",
    cognitiveFunction: "Sequence and gate multi-stage processing",
    biologicalAnalogy: "Dorsolateral prefrontal task set coordinator",
    neuronType: "EXECUTIVE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("pipeline:promote:gold"),
    queueName: "pipeline:promote:gold",
    displayName: "Promote to gold",
    cognitiveFunction: "Elevate vetted records to gold tier",
    biologicalAnalogy: "Memory promotion from hippocampus to cortex",
    neuronType: "EXECUTIVE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("pipeline:promote:bronze-silver"),
    queueName: "pipeline:promote:bronze-silver",
    displayName: "Promote bronze–silver",
    cognitiveFunction: "Intermediate tier transitions",
    biologicalAnalogy: "Staging buffer between sensory and consolidated store",
    neuronType: "EXECUTIVE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("pipeline:monitor"),
    queueName: "pipeline:monitor",
    displayName: "Pipeline monitor",
    cognitiveFunction: "Observe lag, failures, and SLAs",
    biologicalAnalogy: "Ascending reticular activating vigilance",
    neuronType: "EXECUTIVE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("pipeline:error-handler"),
    queueName: "pipeline:error-handler",
    displayName: "Pipeline error handler",
    cognitiveFunction: "Contain and route failed jobs",
    biologicalAnalogy: "Anterior cingulate conflict and error correction",
    neuronType: "EXECUTIVE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: true,
  },
  // Human — HITL
  {
    nodeKey: nodeKeyFromQueue("hitl:escalate"),
    queueName: "hitl:escalate",
    displayName: "HITL escalation",
    cognitiveFunction: "Escalate uncertain cases to human review",
    biologicalAnalogy: "Thalamic relay gating conscious inspection",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 1,
    criticality: "CRITICAL",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("hitl:resume"),
    queueName: "hitl:resume",
    displayName: "HITL resume",
    cognitiveFunction: "Resume automation after human approval",
    biologicalAnalogy: "Re-entry of basal ganglia go signal after hold",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 1,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("maintenance:import-file-cleanup"),
    queueName: "maintenance:import-file-cleanup",
    displayName: "Import file cleanup",
    cognitiveFunction: "Garbage-collect stale import artifacts",
    biologicalAnalogy: "Microglial pruning of synaptic debris",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 1,
    criticality: "LOW",
    pulsing: false,
  },
];

/** Etapa 2 — outreach / social-action (static queues only; per-phone WA queues omitted) */
const E2: CognitiveNodeEntry[] = [
  // Vigilance — quota
  {
    nodeKey: nodeKeyFromQueue("quota:guardian:check"),
    queueName: "quota:guardian:check",
    displayName: "Quota guardian check",
    cognitiveFunction: "Enforce rate and volume limits before send",
    biologicalAnalogy: "Inhibitory interneurons preventing runaway firing",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("quota:guardian:increment"),
    queueName: "quota:guardian:increment",
    displayName: "Quota guardian increment",
    cognitiveFunction: "Book consumption against quotas",
    biologicalAnalogy: "Accumulator neurons tracking resource use",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("quota:guardian:reset"),
    queueName: "quota:guardian:reset",
    displayName: "Quota guardian reset",
    cognitiveFunction: "Reset counters on schedule or policy",
    biologicalAnalogy: "Circadian reset of metabolic counters",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("quota:business-hours:check"),
    queueName: "quota:business-hours:check",
    displayName: "Business hours check",
    cognitiveFunction: "Gate sends to allowed time windows",
    biologicalAnalogy: "Suprachiasmatic timing gate on motor output",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Attention — orchestration
  {
    nodeKey: nodeKeyFromQueue("outreach:orchestrator:dispatch"),
    queueName: "outreach:orchestrator:dispatch",
    displayName: "Outreach dispatch",
    cognitiveFunction: "Dispatch outreach work units to channels",
    biologicalAnalogy: "Parietal priority map for action selection",
    neuronType: "ATTENTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("outreach:orchestrator:router"),
    queueName: "outreach:orchestrator:router",
    displayName: "Outreach router",
    cognitiveFunction: "Route leads across campaigns and strategies",
    biologicalAnalogy: "Superior colliculus routing of orienting responses",
    neuronType: "ATTENTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("outreach:phone:allocator"),
    queueName: "outreach:phone:allocator",
    displayName: "Phone allocator",
    cognitiveFunction: "Bind outbound identity to phone slots",
    biologicalAnalogy: "Basal ganglia channel selection for effectors",
    neuronType: "ATTENTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("outreach:channel:selector"),
    queueName: "outreach:channel:selector",
    displayName: "Channel selector",
    cognitiveFunction: "Choose WA vs email vs other surfaces",
    biologicalAnalogy: "Multimodal integration choosing output modality",
    neuronType: "ATTENTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  // Motor — WA (non per-phone) + email
  {
    nodeKey: nodeKeyFromQueue("q:wa:reply"),
    queueName: "q:wa:reply",
    displayName: "WhatsApp reply",
    cognitiveFunction: "Execute inbound reply handling on shared WA pool",
    biologicalAnalogy: "Alpha motor neurons driving distal musculature",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("wa:message:retry"),
    queueName: "wa:message:retry",
    displayName: "WA message retry",
    cognitiveFunction: "Re-attempt failed WhatsApp deliveries",
    biologicalAnalogy: "Central pattern generator retry bursts",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("wa:chat:history:fetch"),
    queueName: "wa:chat:history:fetch",
    displayName: "WA chat history fetch",
    cognitiveFunction: "Pull thread context for coherent replies",
    biologicalAnalogy: "Efference copy retrieving recent motor sequence",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("wa:status:sync"),
    queueName: "wa:status:sync",
    displayName: "WA status sync",
    cognitiveFunction: "Synchronize delivery and read receipts",
    biologicalAnalogy: "Proprioceptive feedback from effector organs",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("wa:media:send"),
    queueName: "wa:media:send",
    displayName: "WA media send",
    cognitiveFunction: "Transmit attachments and rich payloads",
    biologicalAnalogy: "Fast-twitch motor units for high-bandwidth acts",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("q:email:cold"),
    queueName: "q:email:cold",
    displayName: "Email cold queue",
    cognitiveFunction: "Send cold outbound email at scale",
    biologicalAnalogy: "Phasic burst output along cranial nerve analog",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("email:cold:campaign:create"),
    queueName: "email:cold:campaign:create",
    displayName: "Cold campaign create",
    cognitiveFunction: "Provision new cold sequences",
    biologicalAnalogy: "Motor program compilation before execution",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("email:cold:campaign:pause"),
    queueName: "email:cold:campaign:pause",
    displayName: "Cold campaign pause",
    cognitiveFunction: "Halt sends while preserving state",
    biologicalAnalogy: "Reciprocal inhibition pausing agonist pool",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("email:cold:analytics:fetch"),
    queueName: "email:cold:analytics:fetch",
    displayName: "Cold email analytics",
    cognitiveFunction: "Pull provider metrics for cold mail",
    biologicalAnalogy: "Sensory reafference closing the motor loop",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "LOW",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("email:cold:lead:status"),
    queueName: "email:cold:lead:status",
    displayName: "Cold lead status",
    cognitiveFunction: "Sync lead progression from cold provider",
    biologicalAnalogy: "State feedback updating motor intention model",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("q:email:warm"),
    queueName: "q:email:warm",
    displayName: "Email warm queue",
    cognitiveFunction: "Deliver warm relationship-timed messages",
    biologicalAnalogy: "Smooth tonic motor output for sustained contact",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("email:warm:proforma"),
    queueName: "email:warm:proforma",
    displayName: "Warm proforma email",
    cognitiveFunction: "Send structured commercial documents",
    biologicalAnalogy: "Stereotyped motor synergy for learned gestures",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("email:warm:document"),
    queueName: "email:warm:document",
    displayName: "Warm document email",
    cognitiveFunction: "Attach and track contractual payloads",
    biologicalAnalogy: "Coordinated multi-joint reach-and-grasp analog",
    neuronType: "MOTOR",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Procedural
  {
    nodeKey: nodeKeyFromQueue("template:spintax:process"),
    queueName: "template:spintax:process",
    displayName: "Template spintax",
    cognitiveFunction: "Expand variant text from procedural rules",
    biologicalAnalogy: "Basal ganglia habit sequence unfolding",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("template:personalize"),
    queueName: "template:personalize",
    displayName: "Template personalize",
    cognitiveFunction: "Merge lead facts into message skeletons",
    biologicalAnalogy: "Cerebellar internal model adjusting motor plan",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("template:validate"),
    queueName: "template:validate",
    displayName: "Template validate",
    cognitiveFunction: "Guardrails on content before send",
    biologicalAnalogy: "Premotor constraint checking before execution",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  // Sensory — webhooks (E2)
  {
    nodeKey: nodeKeyFromQueue("webhook:timelinesai:ingest"),
    queueName: "webhook:timelinesai:ingest",
    displayName: "Webhook TimelinesAI",
    cognitiveFunction: "Ingest TimelinesAI callback payloads",
    biologicalAnalogy: "Fast sensory pathway from partner periphery",
    neuronType: "SENSORY",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("webhook:instantly:ingest"),
    queueName: "webhook:instantly:ingest",
    displayName: "Webhook Instantly",
    cognitiveFunction: "Ingest Instantly email events",
    biologicalAnalogy: "Parallel afferent stream for cold-mail telemetry",
    neuronType: "SENSORY",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("webhook:resend:ingest"),
    queueName: "webhook:resend:ingest",
    displayName: "Webhook Resend",
    cognitiveFunction: "Ingest transactional email webhooks",
    biologicalAnalogy: "Cochlear nucleus-like event segmentation",
    neuronType: "SENSORY",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("webhook:normalize"),
    queueName: "webhook:normalize",
    displayName: "Webhook normalize",
    cognitiveFunction: "Normalize heterogeneous webhook shapes",
    biologicalAnalogy: "Primary sensory cortex map alignment",
    neuronType: "SENSORY",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("sequence:schedule:followup"),
    queueName: "sequence:schedule:followup",
    displayName: "Sequence schedule follow-up",
    cognitiveFunction: "Time next touchpoints in nurture flows",
    biologicalAnalogy: "Cerebellar timing for delayed motor acts",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("sequence:stop"),
    queueName: "sequence:stop",
    displayName: "Sequence stop",
    cognitiveFunction: "Terminate sequences on exit criteria",
    biologicalAnalogy: "Stop signal in basal ganglia direct pathway",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("sequence:advance"),
    queueName: "sequence:advance",
    displayName: "Sequence advance",
    cognitiveFunction: "Move lead to next sequence step",
    biologicalAnalogy: "State transition in finite motor grammar",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("sequence:create"),
    queueName: "sequence:create",
    displayName: "Sequence create",
    cognitiveFunction: "Instantiate new cadence graphs",
    biologicalAnalogy: "Motor schema instantiation from library",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("lead:state:transition"),
    queueName: "lead:state:transition",
    displayName: "Lead state transition",
    cognitiveFunction: "Apply FSM transitions on lead lifecycle",
    biologicalAnalogy: "Thalamo-cortical loop updating behavioral state",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("lead:state:validate"),
    queueName: "lead:state:validate",
    displayName: "Lead state validate",
    cognitiveFunction: "Validate guards before state changes",
    biologicalAnalogy: "Striatal gatekeeping of state updates",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("lead:assign:user"),
    queueName: "lead:assign:user",
    displayName: "Lead assign user",
    cognitiveFunction: "Route ownership to human or pool",
    biologicalAnalogy: "Parietal priority map for social targets",
    neuronType: "PROCEDURAL",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Emotion — AI (E2)
  {
    nodeKey: nodeKeyFromQueue("ai:sentiment:analyze"),
    queueName: "ai:sentiment:analyze",
    displayName: "AI sentiment",
    cognitiveFunction: "Infer affective tone of inbound text",
    biologicalAnalogy: "Amygdala valence tagging of linguistic input",
    neuronType: "EMOTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ai:response:generate"),
    queueName: "ai:response:generate",
    displayName: "AI response generate",
    cognitiveFunction: "Draft context-aware replies",
    biologicalAnalogy: "Ventromedial prefrontal social simulation",
    neuronType: "EMOTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("ai:intent:classify"),
    queueName: "ai:intent:classify",
    displayName: "AI intent classify",
    cognitiveFunction: "Map utterances to intent labels",
    biologicalAnalogy: "Insula interoception of communicative goals",
    neuronType: "EMOTION",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  // Vigilance — monitor & alert
  {
    nodeKey: nodeKeyFromQueue("monitor:phone:health"),
    queueName: "monitor:phone:health",
    displayName: "Monitor phone health",
    cognitiveFunction: "Track SIM/channel vitality",
    biologicalAnalogy: "Baroreceptor-like stability monitoring",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("monitor:email:deliverability"),
    queueName: "monitor:email:deliverability",
    displayName: "Monitor email deliverability",
    cognitiveFunction: "Watch bounce and reputation signals",
    biologicalAnalogy: "Chemoreceptor vigilance for toxic buildup",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("monitor:quota:usage"),
    queueName: "monitor:quota:usage",
    displayName: "Monitor quota usage",
    cognitiveFunction: "Observe consumption vs caps",
    biologicalAnalogy: "Hypothalamic energy-budget sensing",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("alert:phone:offline"),
    queueName: "alert:phone:offline",
    displayName: "Alert phone offline",
    cognitiveFunction: "Raise alarm when numbers go dark",
    biologicalAnalogy: "Nociceptive alarm for lost sensory input",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("alert:phone:banned"),
    queueName: "alert:phone:banned",
    displayName: "Alert phone banned",
    cognitiveFunction: "Detect policy blocks on channels",
    biologicalAnalogy: "Pain-like signal from damaged effector pathway",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "CRITICAL",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("alert:bounce:high"),
    queueName: "alert:bounce:high",
    displayName: "Alert high bounce",
    cognitiveFunction: "Escalate unhealthy mail metrics",
    biologicalAnalogy: "Aversive prediction error on expected delivery",
    neuronType: "VIGILANCE",
    swimlane: "social-action",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  // Human — E2
  {
    nodeKey: nodeKeyFromQueue("human:review:queue"),
    queueName: "human:review:queue",
    displayName: "Human review queue",
    cognitiveFunction: "Surface items awaiting human judgment",
    biologicalAnalogy: "Claustral spotlight to conscious workspace",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:review:assign"),
    queueName: "human:review:assign",
    displayName: "Human review assign",
    cognitiveFunction: "Assign review tickets to operators",
    biologicalAnalogy: "Pulvinar routing to frontal eye fields analog",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:takeover:initiate"),
    queueName: "human:takeover:initiate",
    displayName: "Human takeover initiate",
    cognitiveFunction: "Begin human-in-the-loop control session",
    biologicalAnalogy: "Switch from automatic to controlled processing",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "CRITICAL",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:takeover:complete"),
    queueName: "human:takeover:complete",
    displayName: "Human takeover complete",
    cognitiveFunction: "Hand control back to automation",
    biologicalAnalogy: "Release of inhibitory hold on motor cortex",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:approve:message"),
    queueName: "human:approve:message",
    displayName: "Human approve message",
    cognitiveFunction: "Gate outbound content after review",
    biologicalAnalogy: "Final premotor veto before spinal drive",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "CRITICAL",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:review:escalation"),
    queueName: "human:review:escalation",
    displayName: "Human review escalation",
    cognitiveFunction: "Escalate stuck reviews up the hierarchy",
    biologicalAnalogy: "Ascending nociceptive relay for unresolved conflict",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "HIGH",
    pulsing: false,
  },
  {
    nodeKey: nodeKeyFromQueue("human:review:audit-log"),
    queueName: "human:review:audit-log",
    displayName: "Human review audit log",
    cognitiveFunction: "Immutable trace of human decisions",
    biologicalAnalogy: "Declarative episodic log of supervisory acts",
    neuronType: "HUMAN",
    swimlane: "human-oversight",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: false,
  },
  // Pipeline outreach + DLQ
  {
    nodeKey: nodeKeyFromQueue("pipeline:outreach:health"),
    queueName: "pipeline:outreach:health",
    displayName: "Pipeline outreach health",
    cognitiveFunction: "Health checks for outreach subsystem",
    biologicalAnalogy: "Interoceptive summary of motor plant status",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 2,
    criticality: "HIGH",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("pipeline:outreach:metrics"),
    queueName: "pipeline:outreach:metrics",
    displayName: "Pipeline outreach metrics",
    cognitiveFunction: "Emit outreach KPIs and counters",
    biologicalAnalogy: "Autonomic efference copy for telemetry",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 2,
    criticality: "MEDIUM",
    pulsing: true,
  },
  {
    nodeKey: nodeKeyFromQueue("dlq:outreach"),
    queueName: "dlq:outreach",
    displayName: "Outreach DLQ",
    cognitiveFunction: "Quarantine failed outreach jobs",
    biologicalAnalogy: "Glial sequestration of toxic synaptic debris",
    neuronType: "MAINTENANCE",
    swimlane: "pipeline-control",
    etapa: 2,
    criticality: "HIGH",
    pulsing: false,
  },
];

export const COGNITIVE_NODE_CATALOG: ReadonlyArray<CognitiveNodeEntry> = [...E1, ...E2];

export function getNodeByQueueName(queueName: string): CognitiveNodeEntry | undefined {
  return COGNITIVE_NODE_CATALOG.find((n) => n.queueName === queueName);
}

export function getNodesByEtapa(etapa: 1 | 2 | 3 | 4 | 5): CognitiveNodeEntry[] {
  return COGNITIVE_NODE_CATALOG.filter((n) => n.etapa === etapa);
}

export function getNodesBySwimlane(swimlane: Swimlane): CognitiveNodeEntry[] {
  return COGNITIVE_NODE_CATALOG.filter((n) => n.swimlane === swimlane);
}
