import { defineConfig } from "vitest/config";
import { existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

/** Node 22+ / MSW: acces la `localStorage` fără path valid → Warning `--localstorage-file`. */
const nodeLocalStorageBacking = path.join(tmpdir(), "cerniq-web-vitest-localstorage");
if (!existsSync(nodeLocalStorageBacking)) {
  writeFileSync(nodeLocalStorageBacking, "");
}

/** Suprafața Tier B măsurată — vezi `docs/developer-guide/testing-coverage-tiers.json` (@cerniq/web). Restul UI: E2E Playwright + integrare. */
const coverageInclude = [
  "vite.manual-chunks.ts",
  "src/components/brand/CerniqLogo.tsx",
  "src/components/charts/DonutChart.tsx",
  "src/components/charts/GaugeChart.tsx",
  "src/components/charts/LineTrendChart.tsx",
  "src/components/charts/LineTrendDualChart.tsx",
  "src/components/charts/ProgressRing.tsx",
  "src/components/cognitive/neuron-tokens.ts",
  "src/components/cognitive/neurons/index.ts",
  "src/components/data/BulkActionBar.tsx",
  "src/components/data/ChatMessage.tsx",
  "src/components/data/LayerBadge.tsx",
  "src/components/data/ProgressBar.tsx",
  "src/components/data/QueueStatusCard.tsx",
  "src/components/data/StatsBar.tsx",
  "src/components/data/StatusDot.tsx",
  "src/components/dialogs/ConfirmationDialog.tsx",
  "src/components/etapa1/DataQualityScorecard.tsx",
  "src/components/etapa1/DeduplicationReview.tsx",
  "src/components/etapa1/EnrichmentProviderStatus.tsx",
  "src/components/etapa1/pipeline-session.ts",
  "src/components/etapa3/RegenerationAttemptsPanel.tsx",
  "src/components/etapa3/guardrail-violations-chart-utils.ts",
  "src/components/etapa5/NpsGauge.tsx",
  "src/components/etapa5/nps-gauge-utils.ts",
  "src/components/feedback/LoadingPage.tsx",
  "src/components/forms/FormField.tsx",
  "src/components/forms/InputField.tsx",
  "src/components/forms/SearchInput.tsx",
  "src/components/forms/SearchableSelect.tsx",
  "src/components/forms/SelectField.tsx",
  "src/components/layout/Header.tsx",
  "src/components/navigation/Breadcrumbs.tsx",
  "src/components/navigation/CommandPalette.tsx",
  "src/components/navigation/TabsNav.tsx",
  "src/components/outreach/analytics/CampaignAnalytics.tsx",
  "src/components/outreach/phones/PhoneReputationDashboard.tsx",
  "src/components/outreach/sequences/SequenceTimeline.tsx",
  "src/components/outreach/shared/PriorityBadge.tsx",
  "src/components/outreach/shared/stage-config.ts",
  "src/components/ui/badge.tsx",
  "src/components/ui/button.tsx",
  "src/components/ui/card.tsx",
  "src/components/ui/design-tokens-preview.tsx",
  "src/components/ui/dialog.tsx",
  "src/components/ui/index.ts",
  "src/components/ui/input.tsx",
  "src/components/ui/separator.tsx",
  "src/components/ui/skeleton.tsx",
  "src/components/ui/table.tsx",
  "src/components/ui/tabs.tsx",
  "src/components/ui/toast-api.ts",
  "src/components/ui/toast.tsx",
  "src/components/ui/tooltip.tsx",
  "src/config/constants.ts",
  "src/config/navigation-app-parity.ts",
  "src/config/navigation-badge-merge.ts",
  "src/config/navigation-helpers.ts",
  "src/config/navigation.ts",
  "src/hooks/use-app-notifications.ts",
  "src/hooks/use-background-processes.ts",
  "src/hooks/useDebounce.ts",
  "src/lib/analytics-guard.ts",
  "src/lib/auth-roles.ts",
  "src/lib/demo-auth.ts",
  "src/lib/notifications-api.ts",
  "src/lib/refine-auth.ts",
  "src/lib/system-processes-api.ts",
  "src/lib/unified-dashboard-api.ts",
  "src/lib/utils.ts",
  "src/pages/NotFound.tsx",
  "src/pages/auth/ForgotPassword.tsx",
  "src/pages/dashboard/SseLiveBadge.tsx",
  "src/pages/dashboard/constants.ts",
  "src/pages/dashboard/utils.tsx",
  "src/pages/etapa1/settings-integrations.tsx",
  "src/pages/system/workers-fetch.ts",
  "src/providers/theme-context.ts",
  "src/routing/brain-batch-redirect.tsx",
  "src/test-utils/msw/dashboard-stats-fixture.ts",
  "src/test-utils/msw/server.ts",
  "src/types/api.ts",
];

export default defineConfig({
  test: {
    globals: true,
    environment: "jsdom",
    include: ["src/**/*.test.tsx", "__tests__/**/*.test.tsx", "__tests__/**/*.test.ts"],
    setupFiles: ["__tests__/setup.ts"],
    css: true,
    /** Vitest 4: `execArgv` pentru worker-i Node (înlocuiește `poolOptions.*.execArgv`). */
    execArgv: [`--localstorage-file=${nodeLocalStorageBacking}`],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "lcov"],
      reportsDirectory: "./coverage",
      include: coverageInclude,
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
  resolve: { alias: { "@": path.resolve(__dirname, "./src") } },
});
