/**
 * migrate-openbao.test.ts — Teste unitare pentru logica de credential injection OpenBao
 *
 * Acoperire:
 *  - findSecretsFilePath: SECRETS_PATH explicit, search paths, nu găsit
 *  - isSecretsFileReady: marker prezent/absent, fișier lipsă, eroare citire
 *  - waitForOpenBaoReady: ready imediat, ready după N poll-uri, timeout
 *  - applySecretsFile: forceOverwrite=true/false, comentarii, linii goale, KEY=VALUE
 *  - loadMigrationCredentials: OPENBAO_SKIP, OpenBao authoritative, fallback env,
 *    no-file, timeout, ready după așteptare, credențiale lipsă din fișier
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

// ── Imports subiect ────────────────────────────────────────────────────────────
import {
  OPENBAO_READY_MARKER,
  OPENBAO_POLL_INTERVAL_MS,
  OPENBAO_READY_TIMEOUT_MS_DEFAULT,
  SECRETS_SEARCH_PATHS,
  findSecretsFilePath,
  isSecretsFileReady,
  waitForOpenBaoReady,
  applySecretsFile,
  loadMigrationCredentials,
} from "../src/migrate-openbao.js";

// ── Test helpers ───────────────────────────────────────────────────────────────

function makeTempDir(): string {
  const dir = join(tmpdir(), `openbao-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function writeSecretsFile(filePath: string, content: string): void {
  writeFileSync(filePath, content, "utf8");
}

function makeReadySecretsFile(
  filePath: string,
  extra = "DATABASE_DIRECT_URL=postgresql://user:pass@localhost:5432/db\n",
): void {
  writeSecretsFile(
    filePath,
    `# Auto-generated by OpenBao Agent\n${extra}${OPENBAO_READY_MARKER}\n`,
  );
}

// ── Constants ─────────────────────────────────────────────────────────────────

describe("Constants", () => {
  it("OPENBAO_READY_MARKER este 'OPENBAO_SECRETS_LOADED=true'", () => {
    expect(OPENBAO_READY_MARKER).toBe("OPENBAO_SECRETS_LOADED=true");
  });

  it("OPENBAO_POLL_INTERVAL_MS este 500", () => {
    expect(OPENBAO_POLL_INTERVAL_MS).toBe(500);
  });

  it("OPENBAO_READY_TIMEOUT_MS_DEFAULT este 30000", () => {
    expect(OPENBAO_READY_TIMEOUT_MS_DEFAULT).toBe(30_000);
  });

  it("SECRETS_SEARCH_PATHS conține path-urile bind-mount așteptate", () => {
    expect(SECRETS_SEARCH_PATHS).toContain("/opt/cerniq/runtime-secrets/api/api.env");
    expect(SECRETS_SEARCH_PATHS).toContain("/secrets/api.env");
  });
});

// ── findSecretsFilePath ────────────────────────────────────────────────────────

describe("findSecretsFilePath", () => {
  let tmpDir: string;
  let tmpFile: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
    tmpFile = join(tmpDir, "api.env");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("returnează explicit SECRETS_PATH dacă fișierul există", () => {
    writeSecretsFile(tmpFile, "KEY=val");
    const result = findSecretsFilePath(tmpFile);
    expect(result).toBe(tmpFile);
  });

  it("returnează null pentru SECRETS_PATH explicit dacă fișierul nu există", () => {
    const result = findSecretsFilePath("/nonexistent/path/api.env");
    expect(result).toBeNull();
  });

  it("returnează explicit path când fișierul există (explicit SECRETS_PATH)", () => {
    writeSecretsFile(tmpFile, "KEY=val");
    const result = findSecretsFilePath(tmpFile);
    expect(result).toBe(tmpFile);
  });
});

// ── isSecretsFileReady ────────────────────────────────────────────────────────

describe("isSecretsFileReady", () => {
  let tmpDir: string;
  let tmpFile: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
    tmpFile = join(tmpDir, "api.env");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("returnează true când fișierul conține OPENBAO_SECRETS_LOADED=true", () => {
    makeReadySecretsFile(tmpFile);
    expect(isSecretsFileReady(tmpFile)).toBe(true);
  });

  it("returnează false când fișierul există dar nu conține marker-ul", () => {
    writeSecretsFile(tmpFile, "DATABASE_URL=postgresql://localhost/db\n");
    expect(isSecretsFileReady(tmpFile)).toBe(false);
  });

  it("returnează false când fișierul nu există", () => {
    expect(isSecretsFileReady("/nonexistent/path.env")).toBe(false);
  });

  it("returnează false când fișierul este gol", () => {
    writeSecretsFile(tmpFile, "");
    expect(isSecretsFileReady(tmpFile)).toBe(false);
  });

  it("returnează true când marker-ul e pe aceeași linie cu alte chei", () => {
    writeSecretsFile(
      tmpFile,
      "KEY=val\nOPENBAO_SECRETS_LOADED=true\nOPENBAO_SECRETS_TIMESTAMP=1234567890\n",
    );
    expect(isSecretsFileReady(tmpFile)).toBe(true);
  });
});

// ── waitForOpenBaoReady ────────────────────────────────────────────────────────

describe("waitForOpenBaoReady", () => {
  let tmpDir: string;
  let tmpFile: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
    tmpFile = join(tmpDir, "api.env");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("returnează true imediat când fișierul e deja ready", async () => {
    makeReadySecretsFile(tmpFile);
    const sleepFn = vi.fn().mockResolvedValue(undefined);

    const result = await waitForOpenBaoReady(tmpFile, 5000, sleepFn);

    expect(result).toBe(true);
    expect(sleepFn).not.toHaveBeenCalled();
  });

  it("returnează true după N poll-uri când fișierul devine ready", async () => {
    writeSecretsFile(tmpFile, "PARTIAL=data\n");

    let calls = 0;
    const sleepFn = vi.fn().mockImplementation(async () => {
      calls++;
      if (calls >= 3) {
        makeReadySecretsFile(tmpFile);
      }
    });

    const result = await waitForOpenBaoReady(tmpFile, 10_000, sleepFn);

    expect(result).toBe(true);
    expect(sleepFn).toHaveBeenCalledTimes(3);
  });

  it("returnează false la timeout fără marker", async () => {
    writeSecretsFile(tmpFile, "PARTIAL=data\n");

    const sleepFn = vi.fn().mockResolvedValue(undefined);

    vi.useFakeTimers();
    const resultPromise = waitForOpenBaoReady(tmpFile, 500, sleepFn);
    vi.setSystemTime(Date.now() + 600);
    const result = await resultPromise;
    vi.useRealTimers();

    expect(result).toBe(false);
  });

  it("returnează false dacă fișierul nu există deloc după timeout", async () => {
    const sleepFn = vi.fn().mockResolvedValue(undefined);

    vi.useFakeTimers();
    const resultPromise = waitForOpenBaoReady("/nonexistent/file.env", 500, sleepFn);
    vi.setSystemTime(Date.now() + 600);
    const result = await resultPromise;
    vi.useRealTimers();

    expect(result).toBe(false);
  });
});

// ── applySecretsFile ──────────────────────────────────────────────────────────

describe("applySecretsFile", () => {
  let tmpDir: string;
  let tmpFile: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
    tmpFile = join(tmpDir, "api.env");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("parsează KEY=VALUE și aplică în env când forceOverwrite=true", () => {
    writeSecretsFile(
      tmpFile,
      "DATABASE_DIRECT_URL=postgresql://user:pass@host:5432/db\nREDIS_URL=redis://localhost:6379\n",
    );
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, true, env);

    expect(env.DATABASE_DIRECT_URL).toBe("postgresql://user:pass@host:5432/db");
    expect(env.REDIS_URL).toBe("redis://localhost:6379");
  });

  it("suprascrie chei existente când forceOverwrite=true", () => {
    writeSecretsFile(tmpFile, "DATABASE_DIRECT_URL=new-url\n");
    const env: NodeJS.ProcessEnv = { DATABASE_DIRECT_URL: "old-url" };
    applySecretsFile(tmpFile, true, env);

    expect(env.DATABASE_DIRECT_URL).toBe("new-url");
  });

  it("NU suprascrie chei existente când forceOverwrite=false", () => {
    writeSecretsFile(tmpFile, "DATABASE_DIRECT_URL=new-url\n");
    const env: NodeJS.ProcessEnv = { DATABASE_DIRECT_URL: "old-url" };
    applySecretsFile(tmpFile, false, env);

    expect(env.DATABASE_DIRECT_URL).toBe("old-url");
  });

  it("ignoră liniile care încep cu #", () => {
    writeSecretsFile(tmpFile, "# comment\nKEY=value\n# another comment\n");
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, true, env);

    expect(env["# comment"]).toBeUndefined();
    expect(env.KEY).toBe("value");
  });

  it("ignoră liniile goale", () => {
    writeSecretsFile(tmpFile, "\n\nKEY=value\n\n");
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, true, env);

    expect(env.KEY).toBe("value");
    expect(Object.keys(env)).toHaveLength(1);
  });

  it("aplică OPENBAO_SECRETS_LOADED=true marker ca variabilă de env", () => {
    writeSecretsFile(tmpFile, `DATABASE_URL=pg://localhost\n${OPENBAO_READY_MARKER}\n`);
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, true, env);

    expect(env.OPENBAO_SECRETS_LOADED).toBe("true");
    expect(env.DATABASE_URL).toBe("pg://localhost");
  });

  it("aplică chei cu valori care conțin semnul = (ex. URL cu query params)", () => {
    writeSecretsFile(tmpFile, "DATABASE_URL=postgresql://user:pass@host/db?sslmode=require\n");
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, true, env);

    expect(env.DATABASE_URL).toBe("postgresql://user:pass@host/db?sslmode=require");
  });

  it("setează cheile noi când forceOverwrite=false și cheia nu există", () => {
    writeSecretsFile(tmpFile, "NEW_KEY=value\n");
    const env: NodeJS.ProcessEnv = {};
    applySecretsFile(tmpFile, false, env);

    expect(env.NEW_KEY).toBe("value");
  });
});

// ── loadMigrationCredentials ─────────────────────────────────────────────────

describe("loadMigrationCredentials", () => {
  let tmpDir: string;
  let tmpFile: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
    tmpFile = join(tmpDir, "api.env");
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("OPENBAO_SKIP=true cu DATABASE_DIRECT_URL setat → source='env'", async () => {
    const env: NodeJS.ProcessEnv = {
      OPENBAO_SKIP: "true",
      DATABASE_DIRECT_URL: "postgresql://user:pass@host:5432/db",
    };

    const result = await loadMigrationCredentials({ env });

    expect(result.source).toBe("env");
    expect(result.filePath).toBeUndefined();
  });

  it("OPENBAO_SKIP=true fără credențiale → aruncă eroare", async () => {
    const env: NodeJS.ProcessEnv = { OPENBAO_SKIP: "true" };

    await expect(loadMigrationCredentials({ env })).rejects.toThrow(
      /OPENBAO_SKIP=true but neither DATABASE_DIRECT_URL nor DATABASE_URL/,
    );
  });

  it("fișier OpenBao ready → source='openbao', credențiale aplicate", async () => {
    makeReadySecretsFile(
      tmpFile,
      "DATABASE_DIRECT_URL=postgresql://openbao-user:REDACTED@prod:5432/db\n",
    );
    const env: NodeJS.ProcessEnv = { DATABASE_DIRECT_URL: "old-stale-url" };

    const result = await loadMigrationCredentials({ env, secretsPath: tmpFile });

    expect(result.source).toBe("openbao");
    expect(result.filePath).toBe(tmpFile);
    // OpenBao override stale env var
    expect(env.DATABASE_DIRECT_URL).toBe("postgresql://openbao-user:REDACTED@prod:5432/db");
  });

  it("fișier OpenBao ready → suprascrie DATABASE_DIRECT_URL existent din env (OpenBao autoritative)", async () => {
    makeReadySecretsFile(tmpFile, "DATABASE_DIRECT_URL=postgresql://fresh-from-openbao:5432/db\n");
    const env: NodeJS.ProcessEnv = {
      DATABASE_DIRECT_URL: "postgresql://stale-from-shell:5432/db",
    };

    await loadMigrationCredentials({ env, secretsPath: tmpFile });

    expect(env.DATABASE_DIRECT_URL).toBe("postgresql://fresh-from-openbao:5432/db");
  });

  it("fișier OpenBao neready → asteaptă și devine ready → source='openbao'", async () => {
    writeSecretsFile(tmpFile, "DATABASE_DIRECT_URL=postgresql://host/db\n");

    let calls = 0;
    const sleepFn = vi.fn().mockImplementation(async () => {
      calls++;
      if (calls >= 2) {
        makeReadySecretsFile(tmpFile, "DATABASE_DIRECT_URL=postgresql://host/db\n");
      }
    });

    const env: NodeJS.ProcessEnv = {};
    const result = await loadMigrationCredentials({
      env,
      secretsPath: tmpFile,
      sleepFn,
    });

    expect(result.source).toBe("openbao");
    expect(calls).toBeGreaterThanOrEqual(2);
  });

  it("fișier OpenBao neready → timeout → aruncă eroare clară", async () => {
    writeSecretsFile(tmpFile, "PARTIAL=data\n");

    const sleepFn = vi.fn().mockResolvedValue(undefined);

    vi.useFakeTimers();
    const env: NodeJS.ProcessEnv = {
      OPENBAO_READY_TIMEOUT_MS: "500",
    };

    const resultPromise = loadMigrationCredentials({
      env,
      secretsPath: tmpFile,
      sleepFn,
    });
    vi.setSystemTime(Date.now() + 600);
    await expect(resultPromise).rejects.toThrow(/OpenBao secrets file not ready after/);
    vi.useRealTimers();
  });

  it("fișier OpenBao nu există → fallback la env vars → source='fallback'", async () => {
    const env: NodeJS.ProcessEnv = {
      DATABASE_DIRECT_URL: "postgresql://fallback:5432/db",
    };

    const result = await loadMigrationCredentials({
      env,
      secretsPath: "/nonexistent/openbao.env",
    });

    expect(result.source).toBe("fallback");
    expect(result.filePath).toBeUndefined();
  });

  it("fișier nu există și nu există env vars → aruncă eroare", async () => {
    const env: NodeJS.ProcessEnv = {};

    await expect(
      loadMigrationCredentials({ env, secretsPath: "/nonexistent/openbao.env" }),
    ).rejects.toThrow(/No OpenBao secrets file and no DATABASE_DIRECT_URL/);
  });

  it("fișier ready dar fără DATABASE_DIRECT_URL sau DATABASE_URL → aruncă eroare", async () => {
    writeSecretsFile(tmpFile, `JWT_SECRET=some-secret\n${OPENBAO_READY_MARKER}\n`);
    const env: NodeJS.ProcessEnv = {};

    await expect(loadMigrationCredentials({ env, secretsPath: tmpFile })).rejects.toThrow(
      /ready but contains no DATABASE_DIRECT_URL or DATABASE_URL/,
    );
  });

  it("OPENBAO_READY_TIMEOUT_MS din env controlează timeout-ul", async () => {
    writeSecretsFile(tmpFile, "PARTIAL=data\n");

    const sleepFn = vi.fn().mockResolvedValue(undefined);

    vi.useFakeTimers();
    const env: NodeJS.ProcessEnv = { OPENBAO_READY_TIMEOUT_MS: "2000" };

    const resultPromise = loadMigrationCredentials({
      env,
      secretsPath: tmpFile,
      sleepFn,
    });
    vi.setSystemTime(Date.now() + 2100);
    await expect(resultPromise).rejects.toThrow(/2000ms/);
    vi.useRealTimers();
  });

  it("DATABASE_URL (nu DIRECT) este acceptat ca fallback când nu e DIRECT_URL", async () => {
    makeReadySecretsFile(tmpFile, "DATABASE_URL=postgresql://pooler:5432/db\n");
    const env: NodeJS.ProcessEnv = {};

    const result = await loadMigrationCredentials({ env, secretsPath: tmpFile });

    expect(result.source).toBe("openbao");
    expect(env.DATABASE_URL).toBe("postgresql://pooler:5432/db");
  });
});
