{{/*
=============================================================================
OpenBao Agent Template: API Service Environment
=============================================================================
Reference: ADR-0033 OpenBao Secrets Management
Destination: /secrets/api.env
Version: 1.0
=============================================================================
*/}}
# =============================================================================
# Auto-generated by OpenBao Agent - DO NOT EDIT MANUALLY
# Generated: {{ timestamp }}
# Template: api-env.tpl
# =============================================================================

{{- $env := env "CERNIQ_ENV" -}}
{{- with secret "secret/cerniq/api/config" }}
# =============================================================================
# Database Configuration
# =============================================================================
{{- $db := "cerniq" -}}
{{- if eq $env "staging" -}}{{- $db = "cerniq_staging" -}}{{- end -}}
{{- with secret "cerniq-db/creds/api-dynamic" }}
DATABASE_URL=postgresql://{{ .Data.username }}:{{ .Data.password }}@pgbouncer:64033/{{ $db }}
DATABASE_DIRECT_URL=postgresql://{{ .Data.username }}:{{ .Data.password }}@10.0.1.107:5432/{{ $db }}
POSTGRES_USER={{ .Data.username }}
POSTGRES_PASSWORD={{ .Data.password }}
{{- end }}

# =============================================================================
# Redis Configuration
# =============================================================================
# Route Redis via hz.247 internal L4 gateway (fixes VLAN<->vSwitch TCP handshake issues).
REDIS_URL=redis://{{ .Data.redis_username }}:{{ .Data.redis_password }}@10.0.1.10:6379/0
REDIS_PASSWORD={{ .Data.redis_password }}
REDIS_PREFIX={{ .Data.redis_prefix }}
BULLMQ_PREFIX={{ .Data.bullmq_prefix }}

# =============================================================================
# JWT Configuration
# =============================================================================
JWT_SECRET={{ .Data.jwt_secret }}
JWT_REFRESH_SECRET={{ .Data.jwt_secret }}
JWT_ISSUER=cerniq.app
JWT_AUDIENCE=cerniq-api

# =============================================================================
# CORS (restrict in production; * only for dev)
# =============================================================================
{{- if eq $env "staging" }}
CORS_ORIGIN=https://staging.cerniq.app,https://admin.staging.cerniq.app
{{- else if eq $env "production" }}
CORS_ORIGIN=https://cerniq.app,https://admin.cerniq.app
{{- else }}
CORS_ORIGIN=*
{{- end }}
{{- end }}

{{- with secret "secret/cerniq/shared/external" }}
# =============================================================================
# External API Keys
# =============================================================================
{{- $d := .Data -}}
ANAF_CLIENT_ID={{- $v := index $d "anaf_client_id" -}}{{ if $v }}{{ $v }}{{ end }}
ANAF_CLIENT_SECRET={{- $v := index $d "anaf_client_secret" -}}{{ if $v }}{{ $v }}{{ end }}
RESEND_API_KEY={{- $v := index $d "resend_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
HUNTER_API_KEY={{- $v := index $d "hunter_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
TERMENE_API_KEY={{- $v := index $d "termene_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
{{- end }}

# =============================================================================
# OpenBao Metadata
# =============================================================================
OPENBAO_SECRETS_LOADED=true
OPENBAO_SECRETS_TIMESTAMP={{ timestamp }}
