{{/*
=============================================================================
OpenBao Agent Template: API Service Environment
=============================================================================
Reference: ADR-0033 OpenBao Secrets Management
Destination: /secrets/api.env
Version: 1.0
=============================================================================
*/}}
# =============================================================================
# Auto-generated by OpenBao Agent - DO NOT EDIT MANUALLY
# Generated: {{ timestamp }}
# Template: api-env.tpl
# =============================================================================

{{- with secret "secret/data/cerniq/api/config" }}
# =============================================================================
# Database Configuration
# =============================================================================
DATABASE_URL=postgresql://{{ .Data.data.pg_user }}:{{ .Data.data.pg_password }}@pgbouncer:64033/cerniq
POSTGRES_USER={{ .Data.data.pg_user }}
POSTGRES_PASSWORD={{ .Data.data.pg_password }}

# =============================================================================
# Redis Configuration
# =============================================================================
REDIS_URL=redis://:{{ .Data.data.redis_password }}@redis:64039/0
REDIS_PASSWORD={{ .Data.data.redis_password }}

# =============================================================================
# JWT Configuration
# =============================================================================
JWT_SECRET={{ .Data.data.jwt_secret }}
JWT_ISSUER=cerniq.app
JWT_AUDIENCE=cerniq-api
{{- end }}

{{- with secret "secret/data/cerniq/shared/external" }}
# =============================================================================
# External API Keys
# =============================================================================
ANAF_CLIENT_ID={{ .Data.data.anaf_client_id }}
ANAF_CLIENT_SECRET={{ .Data.data.anaf_client_secret }}
RESEND_API_KEY={{ .Data.data.resend_api_key }}
HUNTER_API_KEY={{ .Data.data.hunter_api_key }}
TERMENE_API_KEY={{ .Data.data.termene_api_key }}
{{- end }}

# =============================================================================
# OpenBao Metadata
# =============================================================================
OPENBAO_SECRETS_LOADED=true
OPENBAO_SECRETS_TIMESTAMP={{ timestamp }}
