{{/*
=============================================================================
OpenBao Agent Template: SonarCloud / SonarQube — token analiză (CI + tooling)
=============================================================================
Destination: /secrets/sonar.env (volum host: .../runtime-secrets/ci/sonar.env)
KV v1 path: secret/cerniq/ci/sonar — cheie: token
Nu există consum runtime în API/web; doar scanare și diagnostics:sonar:fetch.
=============================================================================
*/}}
# =============================================================================
# Auto-generated by OpenBao Agent — DO NOT EDIT
# Template: ci-sonar.env.tpl
# =============================================================================
{{- with secret "secret/cerniq/ci/sonar" }}
SONAR_TOKEN={{ .Data.token }}
OPENBAO_SONAR_ENV_RENDERED=true
{{- end }}
