{{/*
=============================================================================
OpenBao Agent Template: PgBouncer config (auth_query, dynamic users)
=============================================================================
Destination: /secrets/pgbouncer.ini
=============================================================================
*/}}
{{- $env := env "CERNIQ_ENV" -}}
# Auto-generated by OpenBao Agent - DO NOT EDIT MANUALLY
# Generated: {{ timestamp }}

[databases]
# Allow both prod/staging databases; clients pick database in connection string.
* = host=10.0.1.107 port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 64033
unix_socket_dir =

# Client auth: fetch SCRAM verifiers from PostgreSQL for Cerniq-only roles.
auth_type = scram-sha-256
auth_dbname = postgres
{{- with secret "secret/cerniq/infra/pgbouncer" }}
auth_user = {{ .Data.auth_user }}
{{- end }}
auth_query = SELECT usename, passwd FROM public.cerniq_pgbouncer_get_auth($1);

# Where PgBouncer reads auth_user password (plaintext).
auth_file = /etc/pgbouncer/userlist.txt

pool_mode = transaction
max_client_conn = 1000
default_pool_size = 50
min_pool_size = 10
reserve_pool_size = 20
reserve_pool_timeout = 5
ignore_startup_parameters = extra_float_digits
server_reset_query = DISCARD ALL

# Log settings
log_connections = 1
log_disconnections = 1
verbose = 0

# Admin users (inside PgBouncer)
admin_users = postgres

