{{/*
=============================================================================
OpenBao Agent Template: Workers Service Environment
=============================================================================
Reference: ADR-0033 OpenBao Secrets Management
Destination: /secrets/workers.env
Version: 1.0
=============================================================================
*/}}
# =============================================================================
# Auto-generated by OpenBao Agent - DO NOT EDIT MANUALLY
# Generated: {{ timestamp }}
# Template: workers-env.tpl
# =============================================================================

{{- with secret "secret/data/cerniq/workers/config" }}
# =============================================================================
# Worker Configuration
# =============================================================================
WORKER_CONCURRENCY={{ .Data.data.worker_concurrency }}
MAX_RETRIES={{ .Data.data.max_retries }}
{{- end }}

{{- with secret "secret/data/cerniq/api/config" }}
# =============================================================================
# Database Configuration
# =============================================================================
DATABASE_URL=postgresql://{{ .Data.data.pg_user }}:{{ .Data.data.pg_password }}@pgbouncer:64033/cerniq
POSTGRES_USER={{ .Data.data.pg_user }}
POSTGRES_PASSWORD={{ .Data.data.pg_password }}

# =============================================================================
# Redis Configuration
# =============================================================================
REDIS_URL=redis://:{{ .Data.data.redis_password }}@redis:64039/0
REDIS_PASSWORD={{ .Data.data.redis_password }}
{{- end }}

{{- with secret "secret/data/cerniq/shared/external" }}
# =============================================================================
# External API Keys (for enrichment workers)
# =============================================================================
ANAF_CLIENT_ID={{ .Data.data.anaf_client_id }}
ANAF_CLIENT_SECRET={{ .Data.data.anaf_client_secret }}
RESEND_API_KEY={{ .Data.data.resend_api_key }}
HUNTER_API_KEY={{ .Data.data.hunter_api_key }}
TERMENE_API_KEY={{ .Data.data.termene_api_key }}
{{- end }}

# =============================================================================
# OpenBao Metadata
# =============================================================================
OPENBAO_SECRETS_LOADED=true
OPENBAO_SECRETS_TIMESTAMP={{ timestamp }}
