{{/*
=============================================================================
OpenBao Agent Template: Workers Service Environment
=============================================================================
Reference: ADR-0033 OpenBao Secrets Management
Destination: /secrets/workers.env
Version: 1.0
=============================================================================
*/}}
# =============================================================================
# Auto-generated by OpenBao Agent - DO NOT EDIT MANUALLY
# Generated: {{ timestamp }}
# Template: workers-env.tpl
# =============================================================================

{{- with secret "secret/cerniq/workers/config" }}
# =============================================================================
# Worker Configuration
# =============================================================================
WORKER_CONCURRENCY={{ .Data.worker_concurrency }}
MAX_RETRIES={{ .Data.max_retries }}
{{- end }}

{{- $env := env "CERNIQ_ENV" -}}
{{- with secret "secret/cerniq/api/config" }}
# =============================================================================
# Database Configuration
# =============================================================================
{{- $db := "cerniq" -}}
{{- if eq $env "staging" -}}{{- $db = "cerniq_staging" -}}{{- end -}}
{{- with secret "cerniq-db/creds/workers-dynamic" }}
DATABASE_URL=postgresql://{{ .Data.username }}:{{ .Data.password }}@pgbouncer:64033/{{ $db }}
POSTGRES_USER={{ .Data.username }}
POSTGRES_PASSWORD={{ .Data.password }}
{{- end }}

# =============================================================================
# Redis Configuration
# =============================================================================
# Route Redis via hz.247 internal L4 gateway (fixes VLAN<->vSwitch TCP handshake issues).
REDIS_URL=redis://{{ .Data.redis_username }}:{{ .Data.redis_password }}@10.0.1.10:6379/0
REDIS_PASSWORD={{ .Data.redis_password }}
REDIS_PREFIX={{ .Data.redis_prefix }}
BULLMQ_PREFIX={{ .Data.bullmq_prefix }}
{{- end }}

{{- with secret "secret/cerniq/shared/external" }}
# =============================================================================
# External API Keys (for enrichment workers)
# =============================================================================
{{- $d := .Data -}}
ANAF_CLIENT_ID={{- $v := index $d "anaf_client_id" -}}{{ if $v }}{{ $v }}{{ end }}
ANAF_CLIENT_SECRET={{- $v := index $d "anaf_client_secret" -}}{{ if $v }}{{ $v }}{{ end }}
RESEND_API_KEY={{- $v := index $d "resend_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
HUNTER_API_KEY={{- $v := index $d "hunter_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
TERMENE_API_KEY={{- $v := index $d "termene_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
ZEROBOUNCE_API_KEY={{- $v := index $d "zerobounce_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
XAI_GROK_API_KEY={{- $v := index $d "xai_grok_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
NOMINATIM_URL={{- $v := index $d "nominatim_url" -}}{{ if $v }}{{ $v }}{{ end }}
ONRC_PORTAL_URL={{- $v := index $d "onrc_portal_url" -}}{{ if $v }}{{ $v }}{{ end }}
HLR_API_KEY={{- $v := index $d "hlr_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
BING_API_KEY={{- $v := index $d "bing_api_key" -}}{{ if $v }}{{ $v }}{{ end }}
ANAF_API_URL={{- $v := index $d "anaf_api_url" -}}{{ if $v }}{{ $v }}{{ end }}
TERMENE_API_URL={{- $v := index $d "termene_api_url" -}}{{ if $v }}{{ $v }}{{ end }}
{{- end }}

# =============================================================================
# OpenBao Metadata
# =============================================================================
OPENBAO_SECRETS_LOADED=true
OPENBAO_SECRETS_TIMESTAMP={{ timestamp }}
