export const MOCK_COMPANIES = [
  {
    id: "1",
    name: "SC Ferma Dunarea SA",
    cui: "RO55443322",
    county: "Ialomita",
    status: "COMPLETED",
    tier: "gold",
    quality: 94,
    anafValid: true,
    termeneValid: true,
    score: 92,
    revenue: "EUR 45,000",
  },
  {
    id: "2",
    name: "Cooperativa Agriland",
    cui: "RO11223344",
    county: "Calarasi",
    status: "PROCESSING",
    tier: "silver",
    quality: 78,
    anafValid: true,
    termeneValid: false,
    score: 71,
    revenue: "EUR 23,000",
  },
  {
    id: "3",
    name: "OUAI Ialomita Nord",
    cui: "RO77889900",
    county: "Ialomita",
    status: "PENDING",
    tier: "bronze",
    quality: 45,
    anafValid: false,
    termeneValid: false,
    score: 34,
    revenue: "EUR 12,000",
  },
  {
    id: "4",
    name: "SC AgroSud SRL",
    cui: "RO44556677",
    county: "Dolj",
    status: "ACTIVE",
    tier: "silver",
    quality: 82,
    anafValid: true,
    termeneValid: true,
    score: 78,
    revenue: "EUR 31,000",
  },
  {
    id: "5",
    name: "SC AgroTech Dunarea",
    cui: "RO12345678",
    county: "Braila",
    status: "COMPLETED",
    tier: "gold",
    quality: 96,
    anafValid: true,
    termeneValid: true,
    score: 95,
    revenue: "EUR 67,000",
  },
];

export const MOCK_LEADS = [
  {
    id: "1",
    company: "SC Ferma Dunarea SA",
    contact: "Ion Popescu",
    status: "WARM_REPLY",
    channel: "WA",
    sentiment: 0.8,
    score: 85,
    timeAgo: "2h ago",
  },
  {
    id: "2",
    company: "Cooperativa Agriland",
    contact: "Maria Ionescu",
    status: "CONTACTED_WA",
    channel: "WA",
    sentiment: 0.5,
    score: 62,
    timeAgo: "5h ago",
  },
  {
    id: "3",
    company: "OUAI Ialomita Nord",
    contact: "Gheorghe Popa",
    status: "COLD",
    channel: "Email",
    sentiment: 0,
    score: 30,
    timeAgo: "1d ago",
  },
  {
    id: "4",
    company: "SC AgroSud SRL",
    contact: "Elena Vasile",
    status: "NEGOTIATION",
    channel: "WA",
    sentiment: 0.9,
    score: 88,
    timeAgo: "30m ago",
  },
  {
    id: "5",
    company: "SC AgroTech Dunarea",
    contact: "Adrian Niculescu",
    status: "CONVERTED",
    channel: "Email",
    sentiment: 1,
    score: 95,
    timeAgo: "3d ago",
  },
];

export const COUNTIES = ["Ialomita", "Calarasi", "Braila", "Dolj", "Teleorman"];
